In [1]:
import sys
import numpy as np
import math
import cv2
import time
from imgProLib import imgProCls


In [3]:
#画像読み込み

fname_in  = "girl2.png"
img = cv2.imread(fname_in)
if img.all() == None:
    print("画像が見つかりません")
pro=imgProCls(img)


In [4]:
#大津法
retImg=pro.OutuMethod()
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [29]:
#誤差分散
retImg=pro.ErrorDiffusionHalfTone()
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
#ガウシアンフィルタ
retImg=pro.GaussianFilter(5,3)
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

-2 -2   -2 -1   -2 0   -2 1   -2 2   
-1 -2   -1 -1   -1 0   -1 1   -1 2   
0 -2   0 -1   0 0   0 1   0 2   
1 -2   1 -1   1 0   1 1   1 2   
2 -2   2 -1   2 0   2 1   2 2   
[[0.0317564  0.03751576 0.03965895 0.03751576 0.0317564 ]
 [0.03751576 0.04431963 0.04685151 0.04431963 0.03751576]
 [0.03965895 0.04685151 0.04952803 0.04685151 0.03965895]
 [0.03751576 0.04431963 0.04685151 0.04431963 0.03751576]
 [0.0317564  0.03751576 0.03965895 0.03751576 0.0317564 ]]
1.0
[[0.0317564  0.03751576 0.03965895 0.03751576 0.0317564 ]
 [0.03751576 0.04431963 0.04685151 0.04431963 0.03751576]
 [0.03965895 0.04685151 0.04952803 0.04685151 0.03965895]
 [0.03751576 0.04431963 0.04685151 0.04431963 0.03751576]
 [0.0317564  0.03751576 0.03965895 0.03751576 0.0317564 ]]


In [4]:
#精鋭化フィルタ
linearF=np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]])
retImg=pro.LinearFilter(linearF)
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[-1 -1 -1]
 [-1  9 -1]
 [-1 -1 -1]]


In [5]:
#ラプラシアンフィルタ
linearF=np.array([[0,1,0],[1,-4,1],[0,1,0]])
retImg=pro.LinearFilter(linearF)
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0  1  0]
 [ 1 -4  1]
 [ 0  1  0]]


In [ ]:
#ラプラシアンフィルタ

retImg=pro.Canny(120,180)
#この3つがそろえば、カーネルが壊れない
cv2.imshow("retImg",retImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#画像書き出し
fname_out = "out.png"
cv2.imwrite(fname_out,retImg)

True